### ISSUE TITLE
ULS UNITS AFRICANA - Visual review and accessibility changes.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#517]
- [x] Remove green color on buttons 
- [x] Disable default colors on elementor
- [x] Disable default fonts on elementor
- [x] Apply right color for separators `<hr>`
- [x] Fix line height on H2s and remove font size from elementor
- [x] Make H2s on home h3s
- [x] All buttons on home page use absolute path, change them too relative
- [x] Fix list left padding across all pages.
- [x] Make font sizes consistent across all pages
- [x]  Fix footer (Warning: Invalid argument supplied for foreach() in /srv/bindings/2e6fcb35534b4084a73a18d6aeeae77d/code/web/wp-content/themes/culu/footer.php on line 100)
- [x] Add consistency on radio buttons. Solid bullets on dot bullets (elementor)? We should use icon lists instead of regular HTML lists for those that don't know HTML.  I am going to go with dot bullets.

From @mbmartini 
Africana checklist: `https://docs.google.com/spreadsheets/d/1Lna_ggdPSmoHZEd9R6Mz1egqMju_U0sneUwqvigf9U8/edit?usp=sharing`

**Comment by manolobevia** [comment]
About `Add consistency on radio buttons. Solid bullets on dot bullets (elementor)? We should use icon lists instead of regular HTML lists for those that don't know HTML.  I am going to go with dot bullets.` I am going to let users add HTML list, since it is a pain to use icon lists in elementor when you have long lists.

**Comment by manolobevia** [comment]
`Fix list left padding across all pages.` This will be fix with the next upstream.

**Comment by manolobevia** [comment]
@kevinkidwell I have noticed we used button links on homepage, we should be consistent and create text links like other sites. Probably the student wanted to replicate the current site.
