### ISSUE TITLE
ULS UNITS MUSIC - Visual review and accessibility changes

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#523]
- [x] Enable all post types on elementor.
- [x] Disable Default Color on elementor.
- [x] Disable Default Fonts on elementor.
- [x] Make ui control icons for elementor accordion consistent with other sites. Choose one icon type and apply all sites. (https://dev-uls-music-library-cornell-edu.pantheonsite.io/research-databases/)
- [x] Apply proper layout to https://dev-uls-music-library-cornell-edu.pantheonsite.io/streaming-audio-video/, https://dev-uls-music-library-cornell-edu.pantheonsite.io/other-music-and-dance-web-sites/
- [x] Provide better visual hierarchy to  https://dev-uls-music-library-cornell-edu.pantheonsite.io/use-the-library/ 
- [x] Make header bottom border color consistent (https://dev-uls-music-library-cornell-edu.pantheonsite.io/)

From @mbmartini 
Music checklist: `https://docs.google.com/spreadsheets/d/1VPmztaeQ1JNFx6OCwVHvuTWCj1w68vaiIyK7C8-TG_8/edit?usp=sharing`

Site has a few more issues than the other ones. Most of these issues are developer related and are related to incorrect use of Aria attributes. there is also one color contrast issue and an ID naming issue as well. On the content side, there's pretty much nothing to fix there.
