### ISSUE TITLE
ULS UNITS MATH - Visual review and accessibility changes.

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#543]
- [x] Home page needs layout adjustments. Add proper left alignment to lists. 
- [x] Make home responsive. Use proper elementor template layout (3 columns)
- [ ] There is no contact info (email/phones) on footer.
- [ ] Font size is not consistent across all pages. Lists have different size fonts compared to body copy
- [ ] Fonts changes for menu, headers, footer etc when `https://dev-uls-mathematics-library-cornell-edu.pantheonsite.io/use-the-library/` is displayed. Also on search display too `https://dev-uls-mathematics-library-cornell-edu.pantheonsite.io/?s=match&search-type-home=site`
- [ ] Make h2 con content wp area h3

From @mbmartini 
Math checklist: `https://docs.google.com/spreadsheets/d/1-jH1pBQLRqELJtYhsPytAln3fBnAUlyZnwIFmpp7glA/edit?usp=sharing`

Site is pretty clean. a few issues left. On the developer side, there's a select box that needs a label and some page landmarks require additional labelling. On the content side, some pages still have repeated links. On the other hand, Siteimprove flagged a few false positive issues that maybe needs to be cleared.
