### ISSUE TITLE
ULS UNITS FINEARTS - Visual review and accessibility changes

### ISSUE THREAD

**Issue by manolobevia** [cul-it/uls#545]
- [x] Wrong font on all pages.

- [x] Make ui control for expanding/collapsing accordion icon consistent across all sites. `https://finearts.library.cornell.edu/resources/`,  https://finearts.library.cornell.edu/jobs/, https://finearts.library.cornell.edu/call-number-and-location-guide/

- [x] Same thing with list bullet styles. Should we use element icons list or html list?

- [x] Add bullets to list here at https://finearts.library.cornell.edu/use-the-library/

- [x] Remove underlines, https://finearts.library.cornell.edu/circulation-policies/ 

- [x] Format copy on home, different size and unnecessary markup used.

- [x] Make accordion consistent with culu theme for https://finearts.library.cornell.edu/jobs/

- [x] This page, `https://finearts.library.cornell.edu/jobs/`, has very poor semantic content. Missing link markup for email. Redo content.

- [x] Change h2 to h3s on https://finearts.library.cornell.edu/databases/

- [x] Inconsistent elementor toggle on `https://finearts.library.cornell.edu/equipment/`

- [x] Use of here label as link in so many pages.

- [ ] Home sidebar (databases and new books), add underline decoration to links.

- [x] Link text used for multiple locations on home (see more). Use aria-label instead of aria-labelledby attribute since there is no ID to use with this aria.

Accessibility Audit
`https://docs.google.com/spreadsheets/d/1mBD8Lzusrbf-d0NulfM_pY8tnyD6suml9Nadtzob01g/edit#gid=776733708`

**Comment by manolobevia** [comment]
@kevinkidwell We are using inconsistently elementor icon list (which is a list) and HTML lists. Both use different bullets. For the user that doesn't know HTML, icon bullets will be ideal. Do we go with icon list or html list?

**Comment by kevinkidwell** [comment]
@manolobevia I think we should stick with the HTML bulleted list instead of the icon list. This way content editors can create them within a Text Editor widget, which will cut down on having to do a bunch of different widgets when they can just use the WYSIWYG editor to do it easily. And then they won't have to bother us to adjust layouts to add a bulleted icon list.

**Comment by manolobevia** [comment]
@kevinkidwell Perfecto!!

**Comment by manolobevia** [comment]
We need to be consistent using elementor toggles or accordion.
![Screen Shot 2019-10-29 at 2 53 26 PM](https://user-images.githubusercontent.com/8395482/67799605-0fc4c600-fa5c-11e9-878e-fdc5e1643988.png)
![Screen Shot 2019-10-29 at 2 50 44 PM](https://user-images.githubusercontent.com/8395482/67799613-12bfb680-fa5c-11e9-9ea1-3933966a76a1.png)

**Comment by kevinkidwell** [comment]
We should use toggles. I'll get a student to look at it and switch that one over.

**Comment by manolobevia** [comment]
In my opinion, I prefer accordion. It looks really good (https://vet.library.cornell.edu/free-animal-health-resources/)
Do you know the difference between accordion and toggle? For me, both have the same functionality.

**Comment by kevinkidwell** [comment]
The difference is that accordions only allow 1 item to be open at once (if you click another it will close the first). Toggle lets you open as many of the items as you want/need. That's why I've been using toggle anywhere that I noticed that type of thing needed used but must have missed some of them.

**Comment by manolobevia** [comment]
I see. It totally makes sense to use toggles.
