### ISSUE TITLE
Asia Pre-Launch Checklist

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#935]
### **Launch Details**
**Tentative launch date**: Jan 18/19
**Upcoming meetings with stakeholders**: Dec 15, Jan 12

### **Developer To-Do**
- [ ] Add Languages to staff profiles - @kevinkidwell (issue needs created)
- [ ] Display of staff profiles based on Collection (department) #912
- [x] Events display for Home and Events pages @manolobevia 
- [ ] Update floor maps - @kevinkidwell (issue needs created)
- [x] Schedule a meeting with Bronwen and Emily about adding Bridging Worlds exhibit to Spotlight - @kevinkidwell 
- [x] Schedule a meeting with content editors (should happen post-launch, but soon after) - @kevinkidwell 
- [ ] Update Broken Links content (dependent upon stakeholder to-do below)
- [x] Update Databases content (dependent upon stakeholder to-do below)
- [x] Add Featured Items for all country/collection pages (dependent upon stakeholder to-do below) - @kevinkidwell (issue needs created)
- [x] Update student employment page content (dependent upon stakeholder to-do below) - @kevinkidwell (issue needs created)
- [x] Update Rawson reading room content (dependent upon stakeholder to-do below) - @kevinkidwell (issue needs created)
- [x] Update  “About”, “Use the Library”, “Services”, and “Collections” pages content (dependent upon stakeholder to-do below) - @kevinkidwell (issue needs created)
- [x] Add copy for the curatorial text boxes for each Southeast Asia country page (dependent upon stakeholder to-do below) - @kevinkidwell (issue needs created)

### **Stakeholder To-Do**
- [ ] Work on the list of Broken Links (excel sheet in box) to either update or remove
- [x] Write copy for the curatorial text boxes for each Southeast Asia country page
- [x] Write copy for the “About”, “Use the Library”, “Services”, and “Collections” pages
- [x] Create lists of featured items for each country/collection page (3 databases, 3 “other resources”, 2 books)
- [x] Find the employment page draft and send to Kevin
- [x] Write the final text about Rawson
- [x] Update Databases content in spreadsheet
